-- AlterTable
ALTER TABLE "Hotel" ALTER COLUMN "area" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "hotel_overview" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "hotel_star_rating" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "latitude" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "longitude" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "mmt_tripadvisor_count" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "pageurl" DROP NOT NULL;
ALTER TABLE "Hotel" ALTER COLUMN "property_address" DROP NOT NULL;
